-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.roles
(
    role_id integer NOT NULL,
    role_name text NOT NULL,
    PRIMARY KEY (role_id)
);

CREATE TABLE public.employees
(
    employee_id integer NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    identity_number text NOT NULL,
    year_birth integer NOT NULL,
    mail text NOT NULL,
    password text NOT NULL,
    enabled boolean,
    PRIMARY KEY (employee_id)
);

CREATE TABLE public.employers
(
    employer_id integer NOT NULL,
    company_name text NOT NULL,
    website text NOT NULL,
    mail text NOT NULL,
    phone_number text NOT NULL,
    password text NOT NULL,
    enabled boolean,
    PRIMARY KEY (employer_id)
);

CREATE TABLE public.system_employees
(
    employee_id integer NOT NULL,
    mail text NOT NULL,
    password text NOT NULL,
    PRIMARY KEY (employee_id)
);

INSERT INTO roles VALUES (1, 'Software Developer');
INSERT INTO roles VALUES (2, 'Software Architect');
INSERT INTO roles VALUES (3, 'Data Scientist');
INSERT INTO roles VALUES (4, 'Project Manager');
INSERT INTO roles VALUES (5, 'Backend Developer');
INSERT INTO roles VALUES (6, 'Frontend Developer');

END;